menu:
  about: /about
  friends: /friends
favicon:
  enable: true
  icon: /image/icon/laoqi_icon.png
profile:
  enable: true
  author: ''
  avatar: '/image/icon/laoqi_icon.png'  # Your avatar image, for example, https://avatars.githubusercontent.com/username
  avatar_link: '' # The link you click on the avatar and jump to, for example, https://github.com/username
  social: # you can customize which and how many social links to show
    - name: Github
      link: 'https://github.com/LaoQiTX' # https://github.com/username
      icon: /image/icon/github.png
    - name: Bilibili
      link: 'https://space.bilibili.com/456265464' # https://space.bilibili.com/youruid
      icon: /image/icon/bilibili.png
music:
  enable: true
  autoplay: false
  songs:
    - title: 'Letter'
      artist: 'Aliya'
      cover: 'https://p1.music.126.net/YDLvbYjfh0Rt0vPsbYaMIA==/109951169721870785.jpg'
      url: 'https://m701.music.126.net/20260418202457/9bea8ce0727999863dcdadc2942f0b19/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/44119056013/0cce/0805/d951/e72a2b8c10b0bea9a7c5daccf884ca51.mp3?vuutv=EEuCO0yu/EQajTNfrF4JzxyFnnfIG5MfsG92WJV3qKKLMV8wcmzjycJwvGhdvSh+GgkLH5CLRdhCRCKeARzGjnBBIyhudrx2Z+BkjpMH+KE='
math:
  enable: true
  engine: mathjax