menu:
  about: /about
  friends: /friends
favicon:
  enable: true
  icon: /image/icon/laoqi_icon.png
profile:
  enable: true
  author: ''
  avatar: '/image/icon/laoqi_icon.png'  # Your avatar image, for example, https://avatars.githubusercontent.com/username
  avatar_link: '' # The link you click on the avatar and jump to, for example, https://github.com/username
  social: # you can customize which and how many social links to show
    - name: Github
      link: 'https://github.com/LaoQiTX' # https://github.com/username
      icon: /image/icon/github.png
    - name: Bilibili
      link: 'https://space.bilibili.com/456265464' # https://space.bilibili.com/youruid
      icon: /image/icon/bilibili.png
music:
  enable: true
  autoplay: false
  songs:
    - title: 'Letter'
      artist: 'Aliya'
      cover: 'https://p1.music.126.net/YDLvbYjfh0Rt0vPsbYaMIA==/109951169721870785.jpg'
      url: '/music/Letter.mp3'
math:
  enable: true
  engine: mathjax